# Generated by Django 2.2.12 on 2020-07-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hookups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
